image: registry.gitlab.com/showcheap/android-ci:T25-B25.0.3

variables:
  ANDROID_SUPPORT_VERSION: "25.4.0"
  GRADLE_USER_HOME: $CI_PROJECT_DIR/.gradle
#  DEFAULT_JVM_OPTS: "-Dhttp.proxyHost=proxy -Dhttp.proxyPort=8080 -Dhttps.proxyHost=proxy -Dhttps.proxyPort=8080"

before_script:
  - source scripts/setup_gradle.sh
  - source scripts/update_android.sh

cache:
  paths:
    - .gradle/wrapper/
    - .gradle/caches/

stages:
  - build
  - test

build:
  stage: build
  script:
    - echo ${ANDROID_HOME}
    - ./gradlew assembleRelease
  artifacts:
    paths:
      - app/build/outputs/
  tags:
      - docker
      - shared
      - innovation


test:
  stage: test
  script:
    - ./gradlew check
  tags:
      - docker
      - shared
      - innovation

